---
- name: ec2 launcher
  hosts: localhost
  connection: local
  tasks:
  - name: launch ec2
    register: ec2
    amazon.aws.ec2:
      instance_type: t2.micro
      key_name: devops_aws_exercise
      image: ami-0a0ad6b70e61be944
      region: us-east-2
      group: devops-aws-exercise
      count: 1
      wait: yes
      instance_tags:
         Name: postgres
  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: launched
    loop: "{{ ec2.instances }}"
  - name: Wait for SSH to come up
    delegate_to: "{{ item.public_dns_name }}"
    wait_for_connection:
      delay: 60
      timeout: 320
    loop: "{{ ec2.instances }}"
 
- name: Configure instance
  hosts: launched
  gather_facts: True
  tasks:
  - name : copy files
    become: yes
    remote_user: ec2-user
    become_method: sudo
    become_user: root
    copy:
      src: "text.txt"
      dest: "/tmp/text.txt"
      owner: ec2-user
      mode: u=rw,g=r,o=r
